# Generated by Django 3.0.2 on 2020-07-13 21:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounts', '0003_bankaccount_group_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaEfector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('hospital', models.CharField(max_length=150)),
                ('fuente', models.CharField(max_length=100)),
                ('observ', models.CharField(max_length=254)),
                ('cobertura', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
